repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        files: '^ema/.*$'
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      -   id: python-no-log-warn
