---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ema-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGLEVEL: "info"
  DEBUG: "true"
  DATABASE_ENGINE: "mysql"
  DATABASE_HOST: "mysql.default.svc.cluster.local"

---
apiVersion: v1
kind: Service
metadata:
  name: ema
spec:
  selector:
    app: ema
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ema
  labels:
    app: ema
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ema
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ema
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: ema-secrets
        - configMapRef:
            name: ema-config
        image: beentageband/ema:alpine
        imagePullPolicy: IfNotPresent
        name: ema
        ports:
        - containerPort: 8000
      initContainers:
      - args: 
        - "-c"
        - "python3 manage.py migrate; python3 manage.py createsuperuser"
        command: ["/bin/sh"]
        envFrom:
        - secretRef:
            name: ema-secrets
        - configMapRef:
            name: ema-config
        image: beentageband/ema:alpine
        imagePullPolicy: IfNotPresent
        name: django-migrate

