---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ema-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_LOGLEVEL: "info"
  DATABASE_ENGINE: "postgresql_psycopg2"
  DATABASE_HOST: "postgres.default.svc.cluster.local"
  DATABASE_NAME: "ema"
  DATABASE_PORT: "5432"
  DJANGO_DEBUG: "true"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_NAME: "ema"

---
apiVersion: v1
kind: Service
metadata:
  name: ema
spec:
  selector:
    app: ema
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ema
  labels:
    app: ema
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ema
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ema
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: ema-secrets
        - configMapRef:
            name: ema-config
        image: beentageband/ema:alpine
        imagePullPolicy: Always
        name: ema
        ports:
        - containerPort: 8000
      initContainers:
      - args: 
        - "-c"
        - "python3 manage.py makemigrations; python3 manage.py migrate"
        command: [ "/bin/sh" ]
        envFrom:
        - secretRef:
            name: ema-secrets
        - configMapRef:
            name: ema-config
        image: beentageband/ema:alpine
        imagePullPolicy: Always
        name: django-migrate

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ema
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ema
  targetCPUUtilizationPercentage: 50

