# Generated by Django 3.0.6 on 2020-06-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Event's name", max_length=100)),
                ('begin_date', models.DateTimeField(help_text='Event begin date, it should be before end date')),
                ('end_date', models.DateTimeField(help_text='Event end date, it should be after begin date')),
                ('location', models.CharField(blank=True, help_text="Event's location. It's as description only", max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='User entry, it should be a unique pair with Event.', max_length=64)),
                ('signup_date', models.DateTimeField(auto_now=True, help_text='Date when signup was created')),
                ('event', models.ForeignKey(help_text='Event entry, it should be a unique pair with User', on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='ema.Event')),
            ],
        ),
        migrations.AddConstraint(
            model_name='signup',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='signup'),
        ),
    ]
