# Generated by Django 3.0.6 on 2020-05-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0001_squashed_0003_auto_20200525_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_up', to='ema.Event'),
        ),
    ]
