# Generated by Django 3.0.6 on 2020-05-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0002_auto_20200525_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=128),
        ),
    ]
