# Generated by Django 3.0.6 on 2020-05-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ema', '0004_auto_20200526_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='ema.Event'),
        ),
    ]
